update public.email_templates
set
  subject = replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(subject, '{{customer_name}}', '{{contact_name}}'),
                '{{lead_name}}',
                '{{contact_name}}'
              ),
              '{{customer_first_name}}',
              '{{contact_first_name}}'
            ),
            '{{lead_first_name}}',
            '{{contact_first_name}}'
          ),
          '{{customer_last_name}}',
          '{{contact_last_name}}'
        ),
        '{{lead_last_name}}',
        '{{contact_last_name}}'
      ),
      '{{customer_email}}',
      '{{contact_email}}'
    ),
    '{{lead_email}}',
    '{{contact_email}}'
  ),
  body_html = replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(
                  replace(
                    replace(
                      replace(
                        replace(
                          replace(
                            replace(
                              replace(
                                replace(body_html, '{{customer_name}}', '{{contact_name}}'),
                                '{{lead_name}}',
                                '{{contact_name}}'
                              ),
                              '{{customer_first_name}}',
                              '{{contact_first_name}}'
                            ),
                            '{{lead_first_name}}',
                            '{{contact_first_name}}'
                          ),
                          '{{customer_last_name}}',
                          '{{contact_last_name}}'
                        ),
                        '{{lead_last_name}}',
                        '{{contact_last_name}}'
                      ),
                      '{{customer_email}}',
                      '{{contact_email}}'
                    ),
                    '{{lead_email}}',
                    '{{contact_email}}'
                  ),
                  '{{customer_phone}}',
                  '{{contact_phone}}'
                ),
                '{{lead_phone}}',
                '{{contact_phone}}'
              ),
              '{{customer_address}}',
              '{{contact_address}}'
            ),
            '{{lead_address}}',
            '{{contact_address}}'
          ),
          '{{customer_message}}',
          '{{contact_message}}'
        ),
        '{{lead_message}}',
        '{{contact_message}}'
      ),
      '{{customer_files}}',
      '{{contact_files}}'
    ),
    '{{lead_files}}',
    '{{contact_files}}'
  ),
  body_text = replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(
                  replace(
                    replace(
                      replace(
                        replace(
                          replace(
                            replace(
                              replace(
                                replace(body_text, '{{customer_name}}', '{{contact_name}}'),
                                '{{lead_name}}',
                                '{{contact_name}}'
                              ),
                              '{{customer_first_name}}',
                              '{{contact_first_name}}'
                            ),
                            '{{lead_first_name}}',
                            '{{contact_first_name}}'
                          ),
                          '{{customer_last_name}}',
                          '{{contact_last_name}}'
                        ),
                        '{{lead_last_name}}',
                        '{{contact_last_name}}'
                      ),
                      '{{customer_email}}',
                      '{{contact_email}}'
                    ),
                    '{{lead_email}}',
                    '{{contact_email}}'
                  ),
                  '{{customer_phone}}',
                  '{{contact_phone}}'
                ),
                '{{lead_phone}}',
                '{{contact_phone}}'
              ),
              '{{customer_address}}',
              '{{contact_address}}'
            ),
            '{{lead_address}}',
            '{{contact_address}}'
          ),
          '{{customer_message}}',
          '{{contact_message}}'
        ),
        '{{lead_message}}',
        '{{contact_message}}'
      ),
      '{{customer_files}}',
      '{{contact_files}}'
    ),
    '{{lead_files}}',
    '{{contact_files}}'
  )
where
  subject like '%{{customer_%'
  or subject like '%{{lead_%'
  or body_html like '%{{customer_%'
  or body_html like '%{{lead_%'
  or body_text like '%{{customer_%'
  or body_text like '%{{lead_%';
